### ISSUE TITLE
Futures trading

### ISSUE THREAD

**Issue by overstartup** [JKorf/Mexc.Net#1]
I appreciate your effort to develop this library.
Could you please check the document. There are help for future and broker. Could you please add these methods too?
https://mexcdevelop.github.io/apidocs/contract_v1_en/

**Comment by JKorf** [comment]
Unfortunately the futures API does not allow managing of orders, it only allows querying data at the moment (see change log of 2022-07-25). So I don't have any immediate plan to implement this at it can't be fully used.

**Comment by overstartup** [comment]
Thanks.
I will contact them to improve it.

**Comment by overstartup** [comment]
it seems they don't have a plan to support it soon.

i know it is not  a good place to ask, but could you please develop the library for bingx , too?
https://bingx-api.github.io/docs/#/en-us/swapV2/changelog

**Comment by JKorf** [comment]
Yes BingX will probably be added in a few weeks :)
