### ISSUE TITLE
GetBookPricesAsync fails with json parsing error (number too big for decimal)

### ISSUE THREAD

**Issue by Arke123** [JKorf/Mexc.Net#10]
**Describe the bug**
The function call GetBookPricesAsync on SPOT fails with the following error:
"Deserialize JsonReaderException: Could not convert string to decimal: 101689396862781574458569716221.53. Path '[2840].bidQty', line 1, position 302918., Path: [2840].bidQty, LineNumber: 1, LinePosition: 302918"

The quantity is too big for a decimal. In this case the causing symbol was DEFM_USDT as the price of the coin is veeery low.

**To Reproduce**
Just call the function GetBookPricesAsync

**Expected behavior**
The function returns a list of the book prices.

**Comment by JKorf** [comment]
Thanks for the report, this has been fixed in the latest version
