### ISSUE TITLE
Issue with placing order 

### ISSUE THREAD

**Issue by alokym86** [JKorf/Mexc.Net#13]
Hello!
I met incorrect behavior, but can't understand the reason. 
The server returns "10007: symbol not support api " while placing order with pretty correct symbol,  like UNIUSDT, LINKUSDT and so on. Here is the url of the request as example (from logs) `https://api.mexc.com/api/v3/order?price=3&quantity=1&side=BUY&signature=15C31EED17EA63F2411DB84969216FE61DC61A19378432194E8144A4F2C98917&symbol=LINKUSDT&timestamp=1723218702117&type=LIMIT`

**To Reproduce**
Provide valid API-key to the `MexcRestClient` and try to place. 

**Expected behavior**
successful response + placed order

**Debug logging**
```
2024.08.09 18:51:41:743 | Trace | Mexc | [Req 3] Sending GET  request to https://api.mexc.com/api/v3/time with headers Accept=[application/json], X-MEXC-APIKEY=[mx0vglndxhTN9im0j1], source=[EASYT]
2024.08.09 18:51:42:083 | Debug | Mexc | [Req 3] 200 - Response received in 335ms: [Data only available when OutputOriginal = true]
2024.08.09 18:51:42:088 | Information | Mexc | Spot Api Time offset within limits, set offset to 0ms
2024.08.09 18:51:42:093 | Information | Mexc | [Req 1] Creating request for https://api.mexc.com/api/v3/order
2024.08.09 18:51:42:123 | Trace | Mexc | [Req 1] Sending POST signed request to https://api.mexc.com/api/v3/order?price=3&quantity=1&side=BUY&signature=15C31EED17EA63F2411DB84969216FE61DC61A19378432194E8144A4F2C98917&symbol=LINKUSDT&timestamp=1723218702117&type=LIMIT with headers Accept=[application/json], X-MEXC-APIKEY=[mx0vglndxhTN9im0j1], source=[EASYT]
2024.08.09 18:51:42:492 | Warning | Mexc | [Req 1] 400 - Error received in 346ms: [ServerError] 10007: symbol not support api 
```

**Comment by JKorf** [comment]
Hi, this is because sadly the API is pretty restricted in what symbol it allows to be traded on. You can use `restClient.SpotApi.ExchangeData.GetApiSymbolsAsync();` to check which symbols are available. For example `BTCUSDT` is not available, but `BTCUSDC` is.

**Comment by alokym86** [comment]
Hi! Thank you for the response. You are right. The problem is in API restrictions.

Thanks again!
