### ISSUE TITLE
MexcStreamTrade missing fields 

### ISSUE THREAD

**Issue by artemtaranych** [JKorf/Mexc.Net#15]
**Describe the bug**
The class MexcStreamTrade missing fields: 
- tradeType 
- dealTime
- eventType
- ClientOrderId

**To Reproduce**
https://mexcdevelop.github.io/apidocs/spot_v3_en/#trade-streams
Request: spot@public.deals.v3.api@<symbol>

**Comment by JKorf** [comment]
All relevant data is available
