### ISSUE TITLE
MexcUserTradeUpdate missing fields

### ISSUE THREAD

**Issue by artemtaranych** [JKorf/Mexc.Net#16]
**Describe the bug**
The class MexcUserTradeUpdate missing fields:
- tradeType
- dealsAmount
- ClientOrderId

**To Reproduce**
https://mexcdevelop.github.io/apidocs/spot_v3_en/#spot-account-deals
Request: spot@private.deals.v3.api

**Comment by JKorf** [comment]
Hi, these fields are available:
tradeType -> TradeSide
dealsAmount -> QuoteQuantity
ClientOrderId -> ClientOrderId

![image](https://github.com/user-attachments/assets/d279971f-0ef9-4bc6-bbcf-ad063991e147)
