### ISSUE TITLE
Question about listenKey management and reconnection behavior

### ISSUE THREAD

**Issue by alexander-bobrov-stealth** [JKorf/Mexc.Net#17]
Hi,
- I have a couple of questions regarding the listenKey management in the Mexc.Net library:
Does the library automatically manage the listenKey for account updates (i.e., does it automatically call the keepAlive API to extend the key's validity), or do I need to handle that manually?
- I noticed in the MexcSocketClientSpotApi.GetReconnectUriAsync function that a new listenKey is generated upon reconnection. If a reconnection happens, does this mean the previous listenKey is invalidated, and I would lose the ability to keep the original key alive?
Thanks for your help!

**Comment by JKorf** [comment]
Hi, these are good questions and actually highlights an issue in the current implementation.
1. The library does not handle the KeepAlive call, the user should call this at an interval
2. The library (possibly, it doesn't always change) generates a new listen key on reconnection, which as you said makes it impossible to call KeepAlive for

I'll do some research on how to fix this.
