### ISSUE TITLE
Disconnection Issue and Credentials Not Passed to GetReconnectUriAsync

### ISSUE THREAD

**Issue by alexander-bobrov-stealth** [JKorf/Mexc.Net#18]
**Description:**

I encountered an issue while subscribing to account updates using the WebSocket client. The stream was created successfully, and the connection was established, but after a disconnection, the connection was not restored automatically.

Here is the code I used:

```
var apiCredentials = GetApiCredentials();

var socketClient = new MexcSocketClient();
socketClient.SetApiCredentials(apiCredentials);

var rest = new MexcRestClient();
rest.SpotApi.SetApiCredentials(apiCredentials);

var request = await rest.SpotApi.Account.StartUserStreamAsync(cancellationToken);

var listenKey = request.Data;
await socketClient.SpotApi.SubscribeToAccountUpdatesAsync(
    listenKey,
    OnUpdateGet,
    cancellationToken);
```
Issue:

Upon debugging, I found that the issue lies in the function **MexcSocketClientSpotApi.GetReconnectUriAsync**. Inside this function, ApiCredentials is null, leading to failure in reconnection.

**Workaround:**

I managed to fix the issue by passing credentials directly via the constructor. This approach works, as shown below:

```
var apiCredentials = GetApiCredentials();

var socketClient = new MexcSocketClient(options =>
{
    options.ApiCredentials = apiCredentials;
});

var rest = new MexcRestClient(options =>
{
    options.ApiCredentials = apiCredentials;
});

var request = await rest.SpotApi.Account.StartUserStreamAsync(cancellationToken);

var listenKey = request.Data;
await socketClient.SpotApi.SubscribeToAccountUpdatesAsync(
    listenKey,
    OnUpdateGet,
    cancellationToken);
```

**Additional question:**

I have an additional question: how can I handle the **listenKey** after a reconnection? If the key becomes invalid after reconnecting, and a new **listenKey** is updated internally by the library, how can I obtain the new one to keep it alive?

Thanks for your help!

**Comment by JKorf** [comment]
Hi, I have a fix for this pending, but it'll be included in a later release. For now the work around you found should work correctly.

As for the additional question that should be answered in your other issue #17

**Comment by alexander-bobrov-stealth** [comment]
Thanks for your help!
