### ISSUE TITLE
no symbol field in the websocket order data

### ISSUE THREAD

**Issue by saiswj** [JKorf/Mexc.Net#2]
https://mexcdevelop.github.io/apidocs/spot_v3_en/#spot-account-deals
spot@private.deals.v3.api

https://mexcdevelop.github.io/apidocs/spot_v3_en/#spot-account-orders
spot@private.orders.v3.api

MexcUserOrderUpdate and MexcUserTradeUpdate no "s"=symbol field

**Comment by JKorf** [comment]
The `Topic` property in the DataEvent update should contain the symbol
