### ISSUE TITLE
IWithdrawRestClient.WithdrawAsync response deserialization bug

### ISSUE THREAD

**Issue by masherak** [JKorf/Mexc.Net#22]
When calling the WithdrawAsync method from the IWithdrawRestClient interface for the Mexc exchange, a JsonSerializationException occurs during response deserialization. The expected return type is IEnumerable<MexcId>, which requires a JSON array. However, the Mexc API returns a JSON object instead, causing the deserialization to fail. This issue only occurs with the Mexc exchange. I have shared logic that works correctly with other exchanges like Binance, Kucoin, and Gate, indicating that the issue is specific to Mexc’s API response format. 

`Deserialize JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IEnumerable`1[Mexc.Net.Objects.Models.Spot.MexcId]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'id', line 1, position 6.`

Version 1.13.1(newest)

The withdrawal proceeds perfectly fine otherwise.

**Comment by JKorf** [comment]
Fixed in latest version
