### ISSUE TITLE
Critical: Incorrect Data Order in User Data WS Stream

### ISSUE THREAD

**Issue by masherak** [JKorf/Mexc.Net#23]
I identified a critical issue with the method IBalanceSocketClient.SubscribeToBalanceUpdatesAsync, where the object IEnumerable<SharedBalance> contains elements in an incorrect order. This problem occurs when my order is filled by multiple orders from the order book. In such cases, several balance update records are received from a single batch, but they appear to be randomly ordered. As a result, the last element in the list does not correspond to the most recent update.

Since the object SharedBalance lacks an ID or timestamp property, it is impossible to reorder the elements on the client side. This causes significant issues in scenarios where precise balance updates are critical for further processing. It is important to note that the same implementation logic works correctly on Binance and Gate exchanges, where updates arrive in the correct sequence.

The issue does not occur when my order is filled by a single matching order or when a withdrawal/deposit is processed — in these cases, updates are properly ordered and processed without any issues.

Version: 1.12.0

<img width="266" alt="image" src="https://github.com/user-attachments/assets/79e3964e-238a-4c28-a619-bd65394d176c">

This is an order where the balance should have only increased because it was a purchase. However, one record, specifically record 3, is smaller, which it simply shouldn’t be. I also figured out how to get the correct balance to all decimal places. You just need to subtract the third record from the second one, then subtract the result from the first record, and you get the exact correct balance. There must be some internal issue, or do you think it could be a problem on Mexc’s side?

UPDATE: So it's not just about the wrong order; the state deteriorates more and more over time.

**Comment by JKorf** [comment]
Hi, I've checked the library, but balance updates are always single balance events. The server sends individual update messages, 1 per balance update, which on the client side gets converter to a singe item array update.
So for Mexc it is never possible that there are multiple balance updates in a single update event.

Could it be perhaps an issue in your own code when updates are received in very quick succession? Otherwise it would have to be an issue on the server side.

**Comment by masherak** [comment]
![image](https://github.com/user-attachments/assets/6364a2b8-8c47-4577-9e98-420d95ff76f0)
![image](https://github.com/user-attachments/assets/a45c3bc9-4522-4d83-9df0-39e0a19170c1)
This logic is as simple as it can be, and message reception wasn’t working properly. Today it seems to be working. I reported the issue with the newly listed token on the day it was launched; maybe the problem was on the server side. Please keep the task open for now; I will monitor it and review your code.

**Comment by masherak** [comment]
@JKorf I used the “OutputOriginalData” switch to see all the raw messages from the server. The messages are correctly ordered by timestamp, but the last one indeed shows a different balance than what the Mexc UI displays. This happens only with one asset, while the others are correct. The issue must be related to the newly listed asset on the server side. The library works fine, so I am closing the issue. Thank you!
