### ISSUE TITLE
MexcTicker model missing return "QuoteVolume"

### ISSUE THREAD

**Issue by haidaulau** [JKorf/Mexc.Net#5]
**Describe the bug**
MexcTicker model missing return "QuoteVolume"

<img width="868" alt="Screenshot 2024-04-03 at 12 38 34" src="https://github.com/JKorf/Mexc.Net/assets/52377037/844a8f82-abb9-4679-a5a2-84e8c09805be">

Please add it. Thanks

**Comment by JKorf** [comment]
Has been added
